e_coli_prediction/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('src.apps.website.urls'))
]

src/apps/website/urls.py
from django.urls import path
from .views import (HomePageView ,predictions,CreekPageView,historical_predictions)

app_name = 'website'
urlpatterns=[

    path('',HomePageView.as_view(),name='home'),
    path('weather-data/', predictions, name='weather_data'),
    path('creekname/<str:creekname>', CreekPageView.as_view(), name='creekname'),
    path('historical/', historical_predictions, name='historical_data'),  # New URL pattern

]

src/apps/website/views.py
import json

import pandas as pd
from django.http import JsonResponse
from django.views.generic import TemplateView
from src.apps.website.weather_analyser.forcast_data import ForecastData
from src.apps.website.weather_analyser.historical_data import HistoricalData
from datetime import datetime, timedelta
from src.apps.website.weather_analyser.predictions import  make_predictions
from src.apps.website.weather_analyser.decorator import check_date
import numpy as np
def _round(value):

    return round(float(value), 2)


class HomePageView(TemplateView):
    template_name = "website/home.html"
    @check_date
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class EagleCreekPageView(TemplateView):
    template_name = "eaglecreek.html"
    @check_date
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

class CreekPageView(TemplateView):
    @check_date
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_template_names(self):
        return [f"creek.html"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        creekname = self.kwargs.get('creekname')
        context['creekname'] = creekname
        return context






def get_season(date):

    if (date.month == 12 and date.day >= 20) or (date.month in [1, 2]) or (date.month == 3 and date.day < 20):
        return 'Winter'
    elif (date.month == 3 and date.day >= 20) or (date.month in [4, 5]) or (date.month == 6 and date.day < 20):
        return 'Spring'
    elif (date.month == 6 and date.day >= 20) or (date.month in [7, 8]) or (date.month == 9 and date.day < 20):
        return 'Summer'
    elif (date.month == 9 and date.day >= 20) or (date.month in [10, 11]) or (date.month == 12 and date.day < 20):
        return 'Fall'
    else:
        return 'Winter'

def predictions(request):
    lat = request.GET.get('lat')
    lon = request.GET.get('lon')
    creek = request.GET.get('creek')
    @check_date
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    if lat and lon:
        forecast_data = ForecastData(latitude=lat, longitude=lon, forecast_days=7)
        metrics = []

        for i in range(7):
            today = datetime.now() + timedelta(days=i)
            today_str = today.strftime('%Y-%m-%d')
            today_data = forecast_data.daily_dataframe[forecast_data.daily_dataframe['date'] == today_str]

            if today_data.empty:
                continue
            temp_max = today_data['temperature_2m_max'].values[0]
            temp_min = today_data['temperature_2m_min'].values[0]
            today_temp_avg = float((temp_max + temp_min) / 2)
            today_precipitation = float(today_data['precipitation_sum'].values[0])
            rainfall = float(today_data['rain_sum'].values[0])

            season = get_season(today)

            metrics.append({
                "date": today_str,
                "Precipitation":_round(today_precipitation),
                "Temp": _round(today_temp_avg),
                "MaxTemp": _round(temp_max),
                "MinTemp": _round(temp_min),
                "Season": season,
                "Rainfall":_round(rainfall)
            })

        print(metrics)
        dates = [entry['date'] for entry in metrics]
        precipitation = [entry['Precipitation'] for entry in metrics]
        temp = [entry['Temp'] for entry in metrics]
        maxTemp = [entry['MaxTemp'] for entry in metrics]
        minTemp = [entry['MinTemp'] for entry in metrics]
        season = [entry['Season'] for entry in metrics]
        rainfall = [entry['Rainfall'] for entry in metrics]


        df = pd.DataFrame({
            "date": dates,
            "Precipitation": precipitation,
            "Temp": temp,
            "MaxTemp": maxTemp,
            "MinTemp": minTemp,
            "Season": season,
        })

        # Generate predictions based on the dataframe
        predictions = make_predictions(creek, df)

        # Combine metrics and predictions
        for i, prediction in enumerate(predictions):
            metrics[i]['prediction'] =int(prediction)

        return JsonResponse(metrics, safe=False)


def historical_predictions(request):
    lat = request.GET.get('lat')
    lon = request.GET.get('lon')
    creek = request.GET.get('creek')
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')

    metrics = []

    if lat and lon and start_date and end_date:
        historical_data = HistoricalData(latitude=lat, longitude=lon, start=start_date, end=end_date)

        # Fetch historical data
        df = historical_data.daily_dataframe

        # Preprocessing data: convert to numeric and remove rows with missing data
        df['temperature_2m_max'] = pd.to_numeric(df['temperature_2m_max'], errors='coerce')
        df['temperature_2m_min'] = pd.to_numeric(df['temperature_2m_min'], errors='coerce')
        df['precipitation_sum'] = pd.to_numeric(df['precipitation_sum'], errors='coerce')

        # Drop rows with NaN values
        df.dropna(subset=['temperature_2m_max', 'temperature_2m_min', 'precipitation_sum'], inplace=True)

        for index, row in df.iterrows():
            date_str = row['date'].strftime('%Y-%m-%d')
            temp_max = row['temperature_2m_max']
            temp_min = row['temperature_2m_min']
            temp_avg = float((temp_max + temp_min) / 2)
            precipitation = float(row['precipitation_sum'])
            season = get_season(row['date'])

            metrics.append({
                "date": date_str,
                "Precipitation": _round(precipitation),
                "Temp": _round(temp_avg),
                "MaxTemp":_round(temp_max),
                "MinTemp":_round(temp_min),
                "Season": season,
            })

        dates = [entry['date'] for entry in metrics]
        precipitation = [entry['Precipitation'] for entry in metrics]
        temp = [entry['Temp'] for entry in metrics]
        maxTemp = [entry['MaxTemp'] for entry in metrics]
        minTemp = [entry['MinTemp'] for entry in metrics]
        season = [entry['Season'] for entry in metrics]

        df = pd.DataFrame({
            "date": dates,
            "Precipitation": precipitation,
            "Temp": temp,
            "MaxTemp": maxTemp,
            "MinTemp": minTemp,
            "Season": season,
        })

        predictions = make_predictions(creek, df)

        for i, prediction in enumerate(predictions):
            metrics[i]['prediction'] = int(prediction)

        return JsonResponse(metrics, safe=False)
    else:
        return JsonResponse({'error': 'Invalid coordinates'}, safe=False)




def weather_data(request):
    lat = request.GET.get('lat')
    lon = request.GET.get('lon')
    creek = request.GET.get('creek')

    if lat and lon:
        forecast_weather = ForecastData(latitude=lat, longitude=lon, forecast_days=7)
        historical_weather = HistoricalData(latitude=lat, longitude=lon, days_back=14)

        metrics = compute_metrics(historical_weather, forecast_weather)

        dates = [entry['date'] for entry in metrics]
        today_avg_temps = [entry['today_avg_temp'] for entry in metrics]
        avg_15_day_temps = [entry['15_day_avg_temp'] for entry in metrics]
        today_precipitations = [entry['today_precipitation'] for entry in metrics]
        avg_10_day_temps = [entry['10_day_avg_temp'] for entry in metrics]
        max_rain = [entry['10_day_rain_sum'] for entry in metrics]
        # 'CDD', 'Precipitation', '15days_Median_Temp', '10days_Median_Temp', 'Max_Rain_10_Days', 'month_date', 'Temp']
        # Creating DataFrame
        df = pd.DataFrame({
            'CDD': today_avg_temps,
            'Precipitation':today_precipitations,
            '15days_Median_Temp': avg_15_day_temps,
            '10days_Median_Temp':avg_10_day_temps,
            'Max_Rain_10_Days':max_rain,
            'month_date':dates,
            'Temp':today_avg_temps
        })
        predictions = make_predictions('fallcreek',df)



        return JsonResponse(metrics, safe=False)

    return JsonResponse({'error': 'Invalid coordinates'}, status=400)





















def compute_metrics(historical_data, forecast_data):
    metrics = []

    for i in range(7):
        today = datetime.now() + timedelta(days=i)
        today_str = today.strftime('%Y-%m-%d')

        # Today's data from forecast
        today_data = forecast_data.daily_dataframe[forecast_data.daily_dataframe['date'] == today_str]
        if today_data.empty:
            continue

        today_temp_avg = float((today_data['temperature_2m_max'].values[0] + today_data['temperature_2m_min'].values[0]) / 2)
        today_precipitation = float(today_data['precipitation_sum'].values[0])

        # 15-day average temperature
        past_15_days = historical_data.daily_dataframe.tail(14)._append(today_data)
        temp_15_days_avg = float((past_15_days['temperature_2m_max'].mean() + past_15_days['temperature_2m_min'].mean()) / 2)

        # 10-day average temperature
        past_10_days = historical_data.daily_dataframe.tail(9)._append(today_data)
        temp_10_days_avg = float((past_10_days['temperature_2m_max'].mean() + past_10_days['temperature_2m_min'].mean()) / 2)

        # 10-day rain sum
        rain_10_days_sum = float(past_10_days['rain_sum'].sum())

        metrics.append({
            "date": today_str,
            "today_avg_temp": today_temp_avg,
            "15_day_avg_temp": temp_15_days_avg,
            "10_day_avg_temp": temp_10_days_avg,
            "10_day_rain_sum": rain_10_days_sum,
            "today_precipitation": today_precipitation,
            "e_coli":"None"
        })
    return metrics

templates/website/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>

    
    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Ubuntu:wght@500;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/weather.css' %}" rel="stylesheet">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StreamE</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    
    
    <style>
        html, body {
            height: 100%;
            margin: 0;
            font-family: Arial, sans-serif;
            overflow-x: hidden;
        }
        body {
            background: url('https://images.pexels.com/photos/2049422/pexels-photo-2049422.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1') no-repeat center center fixed;
            background-size: cover;
            color: #333;
        }
        .overlay {
            position: fixed; /* Fixed position to cover the whole viewport */
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(255, 255, 255, 0.5); /* White background with 50% opacity */
            z-index: 1;
            pointer-events: none; /* Allow clicks through the overlay */
        }
        .content {
            position: relative;
            z-index: 2;
        }
        .navbar {
            background-color: #2d2e83;
            position: fixed;
            width: 100%;
            top: 0;
            z-index: 1000;
        }
        .navbar-brand {
            color: #fff;
            font-size: 1.5rem;
            font-weight: bold;
        }
        .navbar-nav .nav-link {
            color: #fff;
        }
        .navbar-nav .dropdown-menu {
            background-color: #2d2e83;
            color: #fff;
        }
        .navbar-nav .dropdown-menu .dropdown-item {
            color: #fff;
        }
        .navbar-nav .dropdown-menu .dropdown-item:hover {
            background-color: #4547a3;
        }
        .ai-icon {
            color: #f39c12;
        }
        footer {
            background-color: #2d2e83;
            color: #fff;
            padding: 1rem 0;
            text-align: center;
            /* position: fixed; */
            bottom: 0;
            width: 100%;
            z-index: 1000;
        }
        #content-wrapper {
            padding-top: 80px;
            padding-bottom: 60px;
            min-height: calc(100vh - 140px); /* 80px navbar + 60px footer */
            position: relative; /* Ensure content is above the overlay */
        }
        #loader {
            position: fixed;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
            z-index: 10000;
            display: none;
        }
        @media (max-width: 576px) {
            #weather-chart {
                width: 100% !important;
                height: auto !important;
            }
        }
    </style>
</head>
<body>
    <div class="overlay"></div> <!-- Background overlay with opacity -->
    <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href="/">StreamE</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Select Creek
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'website:creekname' creekname='eaglecreek' %}">Eagle Creek</a>
                        <a class="dropdown-item" href="{% url 'website:creekname' creekname='fallcreek' %}">Fall Creek</a>
                        <a class="dropdown-item" href="{% url 'website:creekname' creekname='whitecreek' %}">White Creek</a>
                        <a class="dropdown-item" href="{% url 'website:creekname' creekname='lick' %}">Lick Creek</a>
                        <a class="dropdown-item" href="{% url 'website:creekname' creekname='pogues' %}">Pogues Run</a>
                        <a class="dropdown-item" href="{% url 'website:creekname' creekname='statecreek' %}">State Creek</a>
                        <a class="dropdown-item" href="{% url 'website:creekname' creekname='crooked' %}">Crooked Creek</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
            </ul>
        </div>
    </nav>
    <div id="loader">
        <div class="spinner-border text-primary" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <div id="content-wrapper" class="container mt-5 content">
        {% block content %}
        <canvas id="weather-chart"></canvas>
        {% endblock %}
    </div>
    <footer>
        <p>&copy; 2024 StreamE | Powered by AI <i class="fas fa-robot ai-icon"></i></p>
    </footer>

 
</body>
</html>

templates/website/home.html
{% extends 'website/base.html' %}

{% block content %}
<div class="">
    <h1 class="display-4">Welcome to E. coli Prediction System</h1>
    <p class="lead">Real-time E. coli contamination forecasting for different creeks.</p>
    <hr class="my-4">
    <p>Select a creek from the dropdown menu in the navbar to view the latest E. coli predictions.</p>
</div>

<div class="container">
    <div class="col-md-8">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12 wow fadeIn" data-wow-delay="0.5s">
                    <h1 class="mb-1">Check the weather forecast</h1>
                    <div class="container-fluid py-5">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container_weather">
        <div id="loader" class="d-none text-center">
            <div class="spinner-border" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <div class="weather__header">
            <div class="form-group">
                <label for="location-dropdown">Select Location:</label>
                <select class="form-control" id="location-dropdown">
                    <!-- Options will be populated by JavaScript -->
                </select>
            </div>
     
        </div>
        <div class="weather__body">
            <h1 class="weather__city text-white"></h1>
            <div class="weather__datetime"></div>
            <div class="weather__forecast"></div>
            <div class="col-md-12">
                <h2 id="alert-status">Not Predicted</h2>
            </div>
            <!-- <div class="weather__icon" id="weather-icon"></div> -->
            <img src="https://cdn.pixabay.com/animation/2023/11/11/18/15/18-15-55-407_512.gif" style="width: 60px;height: 60px;"/>
            <!-- <p class="weather__temperature" id="current-temp"></p> -->
            <div class="weather__minmax">
                <p id="min-temp">Min: &#176</p>
                <p id="max-temp">Max: &#176</p>
            </div>
        </div>
        <div class="weather__info">
            <div class="weather__card">
                <i class="fa-solid fa-temperature-full"></i>
                <div>
                    <p>Real Feel</p>
                    <p class="weather__realfeel" id="temp">18&#176</p>
                </div>
            </div>
            <div class="weather__card">
                <i class="fa-solid fa-droplet"></i>
                <div>
                    <p>Precipitation</p>
                    <p class="weather__precipitation" id="precipitation">18&#176</p>
                </div>
            </div>
            <div class="weather__card">
                <i class="fa-solid fa-umbrella"></i>
                <div>
                    <p>Season</p>
                    <p class="weather__season" id="season">18&#176</p>
                </div>
            </div>
            <div class="weather__card">
                <i class="fa-solid fa-cloud-rain"></i>
                <div>
                    <p>Rainfall</p>
                    <p class="weather__rainfall" id="rainfall">18&#176</p>
                </div>
            </div>
        </div>
    </div>

      

    <div class="row">
        <div>
            <h2>About Our System</h2>
            <p>Our E. coli prediction system uses advanced machine learning algorithms to forecast contamination levels in various creeks. By analyzing historical data and environmental factors, we provide accurate and reliable predictions to help you stay safe and informed.</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h2>How to Use the System</h2>
            <p>Follow these simple steps to use our E. coli prediction system:</p>
            <ol>
                <li>Navigate to the top navbar and hover over "Select Creek" to see the dropdown menu.</li>
                <li>Choose your desired creek from the dropdown menu.</li>
                <li>View the current E. coli contamination predictions and take necessary precautions.</li>
                <li>Check back regularly for updated predictions and stay informed about water quality in your area.</li>
            </ol>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-annotation@1.0.0"></script>

<script>
            const creekLocations = {
                "Eagle Creek": [
                    { value: "39.73567,-86.19647", text: "Raymond St" },
                    { value: "39.75048,-86.20769", text: "Morris St" },
                    { value: "39.772,-86.234417", text: "Grande Ave" },
                    { value: "39.780472,-86.259722", text: "10th St." },
                    { value: "39.88778,-86.306917", text: "Lafayette Rd." },
                    { value: "39.925944,-86.278861", text: "Ford Rd." }
                ],
                "Fall Creek": [
                    { value: "39.8355,-86.1182", text: "Fall Creek @ Keystone Ave" },
                    { value: "39.810472,-86.14214", text: "Fall Creek @ 30th St" },
                    { value: "39.805583,-86.1496", text: "Fall Creek @ Central Ave" },
                    { value: "39.8025,-86.159", text: "Fall Creek @ Illinois St" },
                    { value: "39.797167,-86.16942", text: "Fall Creek @ MLK" },
                    { value: "39.781778,-86.17683", text: "Fall Creek @ Indiana Ave" },
                    { value: "39.84472,-86.0679", text: "Devon Creek @ Radnor Rd" },
                    { value: "39.838768,-86.093856", text: "Devon Creek @ Brown Rd" },
                    { value: "39.841028,-86.100944", text: "Devon Creek @ Millersville Rd" }
                ],
                "Lick Creek": [
                    { value: "39.769680,-86.026249", text: "Lick Creek @ Franklin Rd" },
                    { value: "39.746819,-86.063829", text: "Lick Creek @ Arlington Ave" },
                    { value: "39.736023,-86.082626", text: "Lick Creek @ Emerson Ave" },
                    { value: "39.721614,-86.095657", text: "Lick Creek @ Main St" },
                    { value: "39.703886,-86.120591", text: "Lick Creek @ Keystone Ave" },
                    { value: "39.702099,-86.158224", text: "Lick Creek @ Meridian St" },
                    { value: "39.708401,-86.187166", text: "Lick Creek @ Harding St" }
                ],
                "White Creek": [
                    { value: "52.52,13.41", text: "Berlin, Germany" },
                    { value: "40.71,-74.01", text: "New York, USA" },
                    { value: "34.05,-118.24", text: "Los Angeles, USA" },
                    { value: "48.85,2.35", text: "Paris, France" },
                    { value: "35.68,139.69", text: "Tokyo, Japan" }
                ],
                "State Creek": [
                    { value: "39.73131,-86.233", text: "State Ditch @ Bradbury Ave" },
                    { value: "39.72527,-86.2609", text: "Mars Ditch @ Fortune Cir W Dr" },
                    { value: "39.71608,-86.241194", text: "Seerley Creek @ Southwest Dr" },
                    { value: "39.71297,-86.2344", text: "State Ditch @ Mooresville Rd" },
                    { value: "39.69183,-86.232", text: "State Ditch @ Thompson Rd" }
                ],
                "Pogues Run": [
                    { value: "39.756823,-86.173353", text: "White River @ Kentucky Ave" },
                    { value: "39.771778,-86.186278", text: "White River @ New York St" },
                    { value: "39.771,-86.141", text: "Pogues Run @ New York St" },
                    { value: "39.780194,-86.133833", text: "Pogues Run @ 10th St" },
                    { value: "39.787194,-86.116444", text: "Pogues Run @ Rural St" },
                    { value: "39.79625,-86.098639", text: "Pogues Run @ 21st St" },
                    { value: "39.808667,-86.082083", text: "Pogues Run @ Emerson Ave" },
                    { value: "39.825389,-86.065667", text: "Pogues Run @ 38th St" }
                ],
                "Crooked Creek": [
                    { value: "39.797472,-86.042556", text: "Pleasant Run @ 21st St" },
                    { value: "39.775917,-86.064333", text: "Pleasant Run @ Arlington Ave" },
                    { value: "39.752056,-86.075139", text: "Bean Creek @ Orange St" },
                    { value: "39.758167,-86.107611", text: "Pleasant Run @ Southeastern Ave" },
                    { value: "39.729333,-86.120944", text: "Bean Creek @ Keystone Ave" },
                    { value: "39.744111,-86.140944", text: "Pleasant Run @ Barth Ave" },
                    { value: "39.736167,-86.147528", text: "Pleasant Run @ Garfield Park" },
                    { value: "39.735028,-86.148167", text: "Bean Creek @ Garfield Park" },
                    { value: "39.727861,-86.167778", text: "Pleasant Run @ Bluff Rd" },
                    { value: "39.752608,-86.117583", text: "Pleasant Run @ Prospect St" },
                    { value: "39.728917,-86.1395", text: "Bean Creek @ Shelby St" }
                ]
            };

    document.addEventListener('DOMContentLoaded', function() {
        const dropdown = document.getElementById('location-dropdown');
        dropdown.innerHTML = ''; // Clear existing options

        for (const [creek, locations] of Object.entries(creekLocations)) {
            const optgroup = document.createElement('optgroup');
            optgroup.label = creek;

            locations.forEach(function(location) {
                const option = document.createElement('option');
                option.value = location.value;
                option.textContent = location.text;
                optgroup.appendChild(option);
            });

            dropdown.appendChild(optgroup);
        }
    });

    $(document).ready(function() {
        let chart; // To hold the chart instance

        function fetchWeatherData(lat, lon) {
            console.log("FETCHING WEATHER DATA");
            $('#loader').removeClass('d-none'); // Show loader
            $.ajax({
                url: '/weather-data',
                data: {
                    lat: lat,
                    lon: lon,
                    creek: "eaglecreek"
                },
                success: function(data) {
                    $('#loader').addClass('d-none'); // Hide loader
                    let labels = [];
                    let precipitations = [];
                    let temps = [];
                    let maxTemps = [];
                    let minTemps = [];
                    let alerts = [];
                    updateHistoricalTable(data);

                    data.forEach(function(row) {
                        labels.push(row.date);
                        precipitations.push(row.Precipitation);
                        temps.push(row.Temp);
                        maxTemps.push(row.MaxTemp);
                        minTemps.push(row.MinTemp);
                        alerts.push(row.prediction === 1);
                    });

                    // Update UI with fetched data
                    $('#current-temp').html(`${data[0].Temp}&#176`);
                    $('#min-temp').html(`Min: ${data[0].MinTemp}&#176`);
                    $('#max-temp').html(`Max: ${data[0].MaxTemp}&#176`);
                    $('#precipitation').html(`${data[0].Precipitation}  mm`);
                    $('#season').html(`${data[0].Season}`);
                    $('#rainfall').html(`${data[0].Rainfall} mm`);
                    $('#weather-icon').html(`<img src="${data[0].IconUrl}" alt="Weather Icon">`);

                    // Update alert status
                    const alertStatus = data[0].prediction === 1 ? 'Alert Predicted' : 'Alert Not Predicted';
                    const alertColor = data[0].prediction === 1 ? 'red' : 'green';
                    $('#alert-status').html(`Alert Status: ${alertStatus}`).css('color', alertColor);
                },
                error: function() {
                    $('#loader').addClass('d-none'); // Hide loader
                    alert('Failed to fetch weather data');
                }
            });
        }

        // Fetch data for the default location on page load
        let defaultLocation = $('#location-dropdown').val();
        let defaultCoords = defaultLocation.split(',');

        fetchWeatherData(defaultCoords[0], defaultCoords[1]);

        $('#location-dropdown').change(function() {
            let selectedLocation = $(this).val();
            let coords = selectedLocation.split(',');
            fetchWeatherData(coords[0], coords[1]);
        });

        function updateHistoricalTable(data) {
            data.forEach(row => {
                const alert = row.prediction == 1 ? "Yes Alert" : "No Alert";
                const alertColor = row.prediction == 1 ? "red" : "green";

                console.log("TEMPERATURE DATA UPDATED");

                $('#temp').html(`${row.Temp}&#176`);

                const tr = `<tr>
                    <td>${row.date}</td>
                    <td>${row.Temp}</td>
                    <td>${row.MinTemp}</td>
                    <td>${row.MaxTemp}</td>
                    <td>${row.Precipitation}</td>
                    <td>${row.Season}</td>
                    <td style="color: ${alertColor};">${alert}</td>
                </tr>`;
                // tableBody.append(tr);
            });
        }
    });
</script>
{% endblock %}